image: registry.gitlab.com/gschwann/qtandroiddocker:latest

stages:
- build

build:
  stage: build
  script:
    # Decode the keystore file (encrypted via "openssl base64 -A -in GrazWikiKeyStore.jks")
    - echo "$KEYSTORE_FILE" | base64 --decode > GrazWikiKeyStore.jks
    - ./scripts/buildAndroid.sh
    - rm GrazWikiKeyStore.jks
  artifacts:
    paths:
      - build/apk
    expire_in: 15 week
