image: registry.gitlab.com/gschwann/qtandroiddocker:latest

stages:
- build

build:
  stage: build
  script:
    - ./scripts/buildAndroid.sh
  artifacts:
    paths:
      - build/apk
    expire_in: 15 week
